// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  homepage_hero: dynamic(() => import("./HomepageHero")),
  product_grid: dynamic(() => import("./ProductGrid")),
  text_and_image: dynamic(() => import("./TextAndImage")),
  video_block: dynamic(() => import("./VideoBlock")),
};
